# torchtitan Config.toml

[job]
dump_folder = "/pub/nfs-data/mboether/ado_torchtitan"
description = "ado torchtitan"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 10
enable_memory_snapshot = false
save_memory_snapshot_folder = "memory_snapshot"

[metrics]
log_freq = 1
enable_color_printing = true
enable_tensorboard = false
save_tb_folder = "tb"
enable_wandb = true

[model]
name = "llama3"
flavor = "ado"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm / fused_rmsnorm
tokenizer_path = ""

[optimizer]
name = "AdamW"
lr = 0.001
fused = true

[training]
batch_size = 64
seq_len = 1024
warmup_steps = 500
max_norm = 1.0  # grad norm clipping
steps = 60000
data_parallel_replicate_degree = 2
data_parallel_shard_degree = -1 # ?? not sure.
tensor_parallel_degree = 1
compile = true # try=
dataset = ""
seed = 1234

[experimental]
context_parallel_degree = 1
pipeline_parallel_degree = 1
enable_async_tensor_parallel = false

[checkpoint]
enable_checkpoint = true
folder = "checkpoint"
interval_type = "steps"
interval = 5000
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled"  # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'selective'  # ['none', 'selective', 'full']
selective_ac_option = '2'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = false

[comm]
init_timeout_seconds = 600
train_timeout_seconds = 600 # very high timeout for mixtera ops, temp solution, should parallelize some things e.g. fitting of scaling laws