# torchtitan Config.toml

[job]
dump_folder = "/capstor/store/cscs/swissai/a09/mixtera/ado_162m_trainings/torchtitan-dumps-fix"
description = "fix 162m torchtitan"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 10
enable_memory_snapshot = false
save_memory_snapshot_folder = "memory_snapshot"

[metrics]
log_freq = 1
enable_color_printing = true
enable_tensorboard = false
save_tb_folder = "tb"
enable_wandb = true
wandb_project = "ado_experiments"
wandb_run_name = "ado 162m the pile fix mixture"

[model]
name = "llama3"
flavor = "smollm162m"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm / fused_rmsnorm
tokenizer_path = ""

[optimizer]
name = "AdamW"
lr = 0.001
fused = true

[training]
batch_size = 64
seq_len = 2048
warmup_steps = 500
max_norm = 1.0  # grad norm clipping
steps = 30000 # 30k steps because ADO paper uses 1024 context length
data_parallel_replicate_degree = 16
data_parallel_shard_degree = -1 # ?? not sure.
tensor_parallel_degree = 1
compile = true # try=
dataset = ""
seed = 1234
dl_worker = 4
dataloader = "mixtera"
tokenizer = "EleutherAI/gpt-neox-20b"
add_eos = true
add_bos = false

[experimental]
context_parallel_degree = 1
pipeline_parallel_degree = 1
enable_async_tensor_parallel = false

[checkpoint]
enable_checkpoint = true
folder = "checkpoint"
interval_type = "steps"
interval = 2500
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled"  # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'selective'  # ['none', 'selective', 'full']
selective_ac_option = '2'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = false

[comm]
init_timeout_seconds = 3600
train_timeout_seconds = 3600 # very high timeout for mixtera ops, temp solution, should parallelize some things e.g. fitting of scaling laws

[mixtera]
vocab_size = 50432
job_id = "ado_torchtitan_fixmix_162m"
chunk_size = 512
tunnel_via_server = false
chunk_reading_degree_of_parallelism = 1
pile = "default"
